baseurl = "http://semanadasengenharias.com/2017"
title = "3ª Semana das Engenharias (2017)"
languageCode = "pt-br"


theme = "hugo-creative-theme"
googleAnalytics = ""

[params]
# To provide some metadata for search engines feel free to add some
# information about you and your website.
name = "UACSA"
description = "Site do evento Semana das Engenharias, promovido pela Universidade Federal Rural de Pernambuco - Cabo de Santo Agostinho"

# The path must be relative to the static folder
favicon = "favicon.ico"

# You can use Markdown syntax for urls [text](//url.to/source) for
# most longer texts.

# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
# for more icons. The icons are represented by their corresponding
# CSS class.

# All projects of the portfolio are defined in their own files.
# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
# folder into the 'data' directory at the root of this Hugo site.
# For more information take a look at the README.




# Navigation
[params.navigation]
brand = "Semana das Engenharias"

[params.navigation.links]
about     = "Sobre"
services  = "Mini-cursos"
portfolio = "Palestrantes"
contact = "Comissão"

# Hero section
[params.hero]
# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
# slogan     = "3ª Semana das Engenharias"
# subtitle   = '9 a 11 de outubro de 2017'

slogan     = ""
subtitle   = ''
#buttonText = "Find out more"

# Service section
[params.courses]
headline = "Mini-cursos"
summaryText = "Resumo"
teacherText = "Instrutor"
dateText = "Data"

[[params.courses.list]]
modalID = "curso1"
icon = "fa-code"
title = "Técnicas de simulação para projetos de engenharia"
teacher = "Igor Henrique Ferreira Moreno Pinheiro da Silva"
description = "Criação de variáveis, Tipos, Operações com matrizes, Controles de fluxo e laços, Funções úteis, Criação de funções, Gráficos, Aplicações."

[[params.courses.list]]
modalID = "curso2"
icon = "fa-microchip"
title = "Internet Of the Things"
teacher = "Lucas Humenhuk"
description = "A definir."

[[params.courses.list]]
modalID = "curso3"
icon = "fa-envira"
title = "Gestão e Certificação Ambiental Aplicada em Empreendimentos Comerciais"
teacher = "Sergio Maffioletti"
description = "1) Conceitos e Aplicação do Sistema de Gestão Ambiental –SGA;<br />2) Conceitos e Aplicação da Certificação Ambiental em Obras e Operação de Empreendimentos Comerciais;<br />3) Descritivo e Aplicação dos Processos, Práticas e Principais Requisitos para Implantação de Obras Sustentáveis."

[[params.courses.list]]
modalID = "curso4"
icon = "fa-bar-chart"
title = "Análise e detecção de Outliers"
teacher = "José Eduardo Ferreira de Oliveira"
description = "A definir."

[[params.courses.list]]
modalID = "curso5"
icon = "fa-building"
title = "Dimensionamento de pavimento intertravado"
teacher = "Martônio José Marques Francelino"
description = "O termo Pavimento Intertravado tem sido usado, frequentemente, de maneira inadvertida para designar qualquer tipo de pavimento cujo revestimento é constituído por peças pré-moldadas de concreto, às vezes restringindo-se a peças com certos formatos e dimensões. Assim sendo, o minicurso irá abordar as normas técnicas relacionada ao sistema e focará no método de dimensionamento da PCA-84. Além das questões diretamente ligadas ao pavimento em si, faz-se, de forma sucinta, um breve relato quanto às características de sustentabilidade que envolvem a aplicação desse tipo de pavimento."


[[params.courses.list]]
modalID = "curso6"
icon = "fa-car"
title = "Motores de Combustão interna"
teacher = "Vagner Abramchuk"
description = "Tópicos abordados:<ul><li> Desenvolvimento e dimensionamento;</li><li> Combustível;</li><li> O futuro do Etanol;</li><li> Carros Elétricos</li></ul>"

[[params.courses.list]]
modalID = "curso7"
icon = "fa-superpowers"
title = "Desenvolvendo com a plataforma Arduino"
teacher = "Roberto Kenji Hiramatsu"
description = "Neste minicurso será apresentado um passo a passo para desenvolvimento de aplicações. Também, será visto de forma prática alguns princípios para este desenvolvimento e as abordagens para sucesso do desenvolvimento nesta plataforma. Os tópicos práticos básicos abordados são entendimento de entrada/saídas digitais, comunicação serial entre Arduino e computador,  leituras analógicas e interfaceamento com Shields e Sensores."

[[params.courses.list]]
modalID = "curso8"
icon = "fa-cubes"
title = "Introdução a Microcomputadores"
teacher = "Lucas Hartmann"
description = "<b>1. Introdução:</b> Na introdução, será apresentado o hardware de um microprocessador e a metodologia de organização de código. <br /><b>2. Periféricos:</b> Apresentação e configuração de entradas e saídas (GPIO) de um microprocessador. <br /><b>3. Aplicação prática:</b> Apresentação e implementação de uma aplicação utilizando entradas e saídas de um microprocessador."

[[params.courses.list]]
modalID = "curso9"
icon = "fa-handshake-o"
title = "Gerenciamento de Projetos"
teacher = "Daniel Fernandes e Carlos Figueirôa"
description = "Apresentaremos os conceitos fundamentais de gerência de projetos, apresentaremos o cenário atual nesta área, as certificações e como o maior instituto de gerenciamento de projetos do mundo, o PMI, pode ajudar no desenvolvimento profissional. Também será realizado fórum de perguntas e respostas com questões envolvendo a tomada de decisões utilizando o gerenciamento de Projetos."

# Portfolio modals
[params.portfolio]
headline = "Palestrantes"
[params.portfolio.modal]
client = "Client"
date = "Date"
category = "Palestrante"
buttonText = "Fechar"

# Aside section
[params.aside]
headline = "Submissão de trabalhos"
text = "Os artigos científicos para o Congresso de Engenharia devem ser preparados seguindo um destes modelos: [modelo para Word](coeng.doc) ou [modelo para LaTeX](coeng latex.zip). Os artigos aceitos deverão ter pelo menos um autor inscrito no evento."
list = "**[REGRAS DE SUBMISSÃO (clique aqui)](regrassubmissao.pdf)**"
alerta = "oi"

[[params.aside.dates]]
date = "~~6 de agosto~~ 1 de setembro"
what = "Submissão dos trabalhos"

[[params.aside.dates]]
date = "~~4 de setembro~~ 15 de setembro"
what = "Divulgação dos resultados"

[[params.aside.dates]]
date = "~~18 de setembro~~ 22 de setembro"
what = "Envio da versão final dos trabalhos aceitos"

[params.aside.button]
text = "Submeter trabalho"
link = "https://www.even3.com.br/participante/trabalhocientifico/"

# About section
[params.about]
headline    = "Sobre o evento"
description = "A Semana das Engenharias da UACSA, em sua terceira edição, apresentará um caráter mais abrangente, contemplando o II Congresso de Engenharias da UACSA. Este evento reafirma o caráter interdisciplinar da Unidade ao propor uma programação diversificada, contando com a participação de profissionais das mais diversas áreas da Engenharia ligados a instituições do país e do exterior. Além da comunidade acadêmica, os profissionais que trabalham nas indústrias dos arredores também serão motivados a apresentar seus trabalhos no Congresso e a contribuir em mesas-redondas, palestras e minicursos do evento. Com o objetivo de estimular a participação ativa dos estudantes de graduação da UACSA, a III Semana das Engenharias também contará com a apresentação de projetos desenvolvidos pelos alunos de graduação da Unidade e com competições/desafios acadêmicos."
#buttonText  = "Get started!"

# Contact section
[params.contact]
headline = "Comissão organizadora"
description = "[Última atualização: 31/07/2017](comissao.pdf)"
phone = "+55 81 3512 5808"
email = "seeng2017@gmail.com"

# Google Maps section
# [params.location]
# 	latitude  = "34.007850"
# 	longitude = "-118.499305"
# 	maps_api_key = ""
